[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "humann3-tools"
version = "0.2.0"
description = "A comprehensive Python package for assigning raw metagenomic sequence reads to microbial gene and pathway databases using HUMAnN3, followed by downstream processing and analysis"
readme = "README.md"
requires-python = ">=3.12"
license = {text = "MIT"}
authors = [
    {name = "David Haslam", email = "dhaslam@gmail.com"}
]
maintainers = [
    {name = "David Haslam", email = "dhaslam@gmail.com"}
]
keywords = ["microbiome", "metagenomics", "humann3", "kneaddata", "bioinformatics"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]

dependencies = [
    "pandas>=1.3.0",
    "numpy>=1.20.0",
    "matplotlib>=3.4.0",
    "seaborn>=0.11.0",
    "scipy>=1.7.0",
    "scikit-learn>=1.0.0",
    "statsmodels>=0.13.0",
    "scikit-posthocs>=0.7.0",
    "scikit-bio>=0.5.6",
    "tqdm>=4.62.0",
    "psutil>=5.8.0",
    "biopython>=1.79",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=3.0.0",
    "black>=22.3.0",
    "isort>=5.10.0",
    "flake8>=4.0.0",
    "mypy>=0.950",
]

docs = [
    "sphinx>=4.5.0",
    "sphinx-rtd-theme>=1.0.0",
    "nbsphinx>=0.8.8",
]

[project.urls]
"Homepage" = "https://github.com/dhaslam/humann3_tools"
"Bug Tracker" = "https://github.com/dhaslam/humann3_tools/issues"
"Documentation" = "https://github.com/dhaslam/humann3_tools/blob/main/README.md"

[project.scripts]
humann3-tools = "humann3_tools.cli:main"
humann3-kneaddata = "humann3_tools.kneaddata_cli:main"
humann3-run = "humann3_tools.humann3_run_cli:main"
humann3-preprocess = "humann3_tools.preprocessing.preprocessing_cli:main"
humann3-join = "humann3_tools.humann3.join_cli:main"
humann3-diff = "humann3_tools.analysis.differential_abundance_cli:main"
humann3-stats = "humann3_tools.analysis.statistical_cli:main"
humann3-viz = "humann3_tools.analysis.visualize_cli:main"
join_unstratify_humann_output = "humann3_tools.humann3.join_unstratify:join_unstratify_humann_output"

[tool.setuptools]
package-dir = {"" = "."}
packages = ["humann3_tools"]

[tool.setuptools.package-data]
"humann3_tools" = ["py.typed", "*.md"]

[tool.black]
line-length = 100
target-version = ["py38", "py39", "py310", "py312"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 100

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
